/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informacion;


import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Action;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AndEsala
 */
public class appBanco extends javax.swing.JFrame {

    /**
     * Creates new form appBanco
     */
    Cuentas miCuenta = new Cuentas();     
    public int cantOper = 0;
    
    public appBanco() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Group1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        historial = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btn_retiro = new javax.swing.JRadioButton();
        btn_deposito = new javax.swing.JRadioButton();
        ver_saldo = new javax.swing.JLabel();
        bal_saldo = new javax.swing.JButton();
        dato = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Confirma = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        btn_info = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Banco ABCD");

        historial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo transacción", "Valor", "Saldo total", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(historial);
        if (historial.getColumnModel().getColumnCount() > 0) {
            historial.getColumnModel().getColumn(0).setResizable(false);
            historial.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Balance de cuenta:");
        jLabel4.setFocusCycleRoot(true);

        Group1.add(btn_retiro);
        btn_retiro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_retiro.setText("Retirar");
        btn_retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_retiroActionPerformed(evt);
            }
        });

        Group1.add(btn_deposito);
        btn_deposito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_deposito.setText("Consignar");
        btn_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_depositoActionPerformed(evt);
            }
        });

        ver_saldo.setBackground(new java.awt.Color(204, 204, 255));
        ver_saldo.setText("$");
        ver_saldo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        ver_saldo.setFocusCycleRoot(true);

        bal_saldo.setText("Consultar");
        bal_saldo.setFocusCycleRoot(true);
        bal_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bal_saldoActionPerformed(evt);
            }
        });

        dato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Digite valor:");

        Confirma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Confirma.setText("Confirmar");
        Confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmaActionPerformed(evt);
            }
        });

        Salir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Fecha:");

        fecha.setEditable(false);
        fecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaActionPerformed(evt);
            }
        });

        btn_info.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btn_info.setText("Ver Info");
        btn_info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_infoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btn_info)
                                        .addGap(18, 18, 18)
                                        .addComponent(Salir))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(ver_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(bal_saldo))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_retiro)
                                .addGap(18, 18, 18)
                                .addComponent(btn_deposito))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Confirma)
                                    .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_deposito, btn_retiro});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Salir)
                            .addComponent(btn_info))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bal_saldo)
                            .addComponent(ver_saldo)
                            .addComponent(jLabel4)))
                    .addComponent(jLabel1))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_retiro)
                    .addComponent(btn_deposito))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Confirma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_deposito, btn_retiro});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bal_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bal_saldoActionPerformed
                   
    ver_saldo.setText("$ "+miCuenta.consultasaldo());
    super.update(this.getGraphics());
    }//GEN-LAST:event_bal_saldoActionPerformed

    private void btn_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_depositoActionPerformed
         
    }//GEN-LAST:event_btn_depositoActionPerformed

    private void ConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmaActionPerformed
          
       DefaultTableModel model = (DefaultTableModel) historial.getModel();             
             
             fecha.setText(miCuenta.lf());
             float valor = Float.parseFloat(dato.getText()); // Extraer valor transacción
             String retiro = btn_retiro.getText();
             String consignar = btn_deposito.getText();
            
             
             if(btn_retiro.isSelected()){ // Al seleccionar RETIRO  
                     cantOper++;   
                     miCuenta.transaccion(retiro, valor); 
                     dato.setText("");
                                
                     if (cantOper > 4) {
                        JOptionPane.showMessageDialog(null, "**Usted ha superado el número de retiros diarios**"
                                + "\n Nro. de intentos de retiro:  "+ (cantOper));
                        btn_retiro.setEnabled(false);
                    } 
                     if(miCuenta.consultasaldo()== 0 ){
                        btn_retiro.setEnabled(false);
                    }               
                   
                }else if(btn_deposito.isSelected()){// Al seleccionar COSIGNAR                 
                    miCuenta.transaccion(consignar, valor);
                    dato.setText("");
                    if(miCuenta.consultasaldo()>0 && cantOper < 4){
                        btn_retiro.setEnabled(true);
                    }
             }
           
           if(valor>0){ //valido
                String tipo = miCuenta.Gettipo(),
                fech = miCuenta.lf();   
                float valortrans = miCuenta.getvalortransaccion(),
                saldoTotal = miCuenta.consultasaldo();
                
            Object[] registro = new Object[4];
            registro[0] = tipo;
            registro[1] = valortrans;
            registro[2] = saldoTotal;
            registro[3] = fech;

            model.addRow(registro);
            historial.setModel(model);
           }
        
    }//GEN-LAST:event_ConfirmaActionPerformed

    private void btn_retiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_retiroActionPerformed
         
    }//GEN-LAST:event_btn_retiroActionPerformed

    private void datoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoActionPerformed
        
    }//GEN-LAST:event_datoActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        this.dispose();  //Cerrar ventana
            JOptionPane.showMessageDialog(null, "Gracias por usar nuestro banco");
    }//GEN-LAST:event_SalirActionPerformed

    private void btn_infoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_infoActionPerformed
      
           infoCliente infoC = new infoCliente(this, true); // "This es el padre" y True           
           infoC.setLocationRelativeTo(null);
            infoC.show();
    }//GEN-LAST:event_btn_infoActionPerformed

    private void fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaActionPerformed
       
    }//GEN-LAST:event_fechaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appBanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new appBanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Confirma;
    private javax.swing.ButtonGroup Group1;
    private javax.swing.JButton Salir;
    private javax.swing.JButton bal_saldo;
    private javax.swing.JRadioButton btn_deposito;
    private javax.swing.JButton btn_info;
    private javax.swing.JRadioButton btn_retiro;
    private javax.swing.JTextField dato;
    private javax.swing.JTextField fecha;
    private javax.swing.JTable historial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ver_saldo;
    // End of variables declaration//GEN-END:variables
}
